import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'English' | 'Spanish' | 'French' | 'German' | 'Chinese';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = '@health_companion_language';

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  English: {
    'auth.welcome_back': 'Welcome Back!',
    'auth.create_account': 'Create Account',
    'auth.sign_in_continue': 'Sign in to continue your health journey',
    'auth.create_get_started': 'Create your account to get started with personalized care',
    'auth.first_name': 'First Name',
    'auth.last_name': 'Last Name',
    'auth.email': 'Email Address',
    'auth.phone': 'Phone Number (Optional)',
    'auth.password': 'Password',
    'auth.confirm_password': 'Confirm Password',
    'auth.sign_in': 'Sign In',
    'auth.create_account_btn': 'Create Account',
    'auth.senior_looking': 'A senior looking for health support',
    'auth.caregiver': 'A caregiver or family member',
    'auth.sign_up': "Don't have an account? Sign Up",
    'auth.sign_in_prompt': 'Already have an account? Sign In',
    'auth.i_am': 'I am:',
    'main.welcome': 'Welcome',
    'main.ai_companion': 'AI-powered health companion',
    'main.monitor': 'Monitor',
    'main.activities': 'Activities',
    'main.medication': 'Medication',
    'main.dashboard': 'Dashboard',
    'main.chat_ai': 'Chat with AI',
    'main.ai_easy': 'Let AI make things easy',
    'main.logout': 'Logout',
    'settings.title': 'Settings',
    'settings.accessibility': 'Accessibility',
    'settings.font_size': 'Font Size',
    'settings.large_text': 'Large Text',
    'settings.large_text_desc': 'Increase text size for better readability',
    'settings.high_contrast': 'High Contrast Mode',
    'settings.high_contrast_desc': 'Enhanced contrast for better visibility',
    'settings.voice_feedback': 'Voice Feedback',
    'settings.voice_feedback_desc': 'Audio confirmation for actions',
    'settings.haptic_feedback': 'Haptic Feedback',
    'settings.haptic_feedback_desc': 'Vibration feedback for touch interactions',
    'settings.notifications': 'Notifications',
    'settings.medication_reminders': 'Medication Reminders',
    'settings.medication_reminders_desc': 'Get notified when it\'s time to take medication',
    'settings.health_check_reminders': 'Health Check Reminders',
    'settings.health_check_reminders_desc': 'Reminders for regular health monitoring',
    'settings.activity_reminders': 'Activity Reminders',
    'settings.activity_reminders_desc': 'Gentle reminders for daily activities',
    'settings.emergency_alerts': 'Emergency Alerts',
    'settings.emergency_alerts_desc': 'Critical health and safety notifications',
    'settings.quiet_hours': 'Quiet Hours',
    'settings.privacy_sharing': 'Privacy & Sharing',
    'settings.share_family': 'Share with Family',
    'settings.share_family_desc': 'Allow family members to view your health data',
    'settings.share_doctor': 'Share with Doctor',
    'settings.share_doctor_desc': 'Allow healthcare providers to access your data',
    'settings.location_tracking': 'Location Tracking',
    'settings.location_tracking_desc': 'Track location for emergency services',
    'settings.data_backup': 'Data Backup',
    'settings.data_backup_desc': 'Automatically backup your health data',
    'settings.app_preferences': 'App Preferences',
    'settings.language': 'Language',
    'settings.time_format': 'Time Format',
    'settings.auto_lock': 'Auto Lock',
    'settings.data_account': 'Data & Account',
    'settings.export_data': 'Export Data',
    'settings.export_data_desc': 'Download your health data',
    'settings.reset_settings': 'Reset Settings',
    'settings.reset_settings_desc': 'Restore default settings',
    'settings.delete_account': 'Delete Account',
    'settings.delete_account_desc': 'Permanently delete your account',
    'font_size.title': 'Font Size',
    'font_size.desc': 'Adjust the text size throughout the app for better readability.',
    'font_size.small': 'Small (85%)',
    'font_size.small_desc': 'Recommended for compact screens',
    'font_size.medium': 'Medium (100%)',
    'font_size.medium_desc': 'Default size',
    'font_size.large': 'Large (125%)',
    'font_size.large_desc': 'Easier to read',
    'font_size.extra_large': 'Extra Large (150%)',
    'font_size.extra_large_desc': 'Maximum readability',
  },
  Spanish: {
    'auth.welcome_back': '¡Bienvenido de nuevo!',
    'auth.create_account': 'Crear cuenta',
    'auth.sign_in_continue': 'Inicia sesión para continuar tu viaje de salud',
    'auth.create_get_started': 'Crea tu cuenta para comenzar con atención personalizada',
    'auth.first_name': 'Nombre',
    'auth.last_name': 'Apellido',
    'auth.email': 'Correo electrónico',
    'auth.phone': 'Número de teléfono (Opcional)',
    'auth.password': 'Contraseña',
    'auth.confirm_password': 'Confirmar contraseña',
    'auth.sign_in': 'Iniciar sesión',
    'auth.create_account_btn': 'Crear cuenta',
    'auth.senior_looking': 'Un adulto mayor buscando apoyo de salud',
    'auth.caregiver': 'Un cuidador o familiar',
    'auth.sign_up': '¿No tienes una cuenta? Regístrate',
    'auth.sign_in_prompt': '¿Ya tienes una cuenta? Inicia sesión',
    'auth.i_am': 'Soy:',
    'main.welcome': 'Bienvenido',
    'main.ai_companion': 'Compañero de salud con IA',
    'main.monitor': 'Monitorear',
    'main.activities': 'Actividades',
    'main.medication': 'Medicación',
    'main.dashboard': 'Panel',
    'main.chat_ai': 'Chatear con IA',
    'main.ai_easy': 'Deja que la IA facilite las cosas',
    'main.logout': 'Cerrar sesión',
    'settings.title': 'Configuración',
    'settings.accessibility': 'Accesibilidad',
    'settings.font_size': 'Tamaño de fuente',
    'settings.large_text': 'Texto grande',
    'settings.large_text_desc': 'Aumentar el tamaño del texto para mejor legibilidad',
    'settings.high_contrast': 'Modo de alto contraste',
    'settings.high_contrast_desc': 'Contraste mejorado para mejor visibilidad',
    'settings.voice_feedback': 'Retroalimentación de voz',
    'settings.voice_feedback_desc': 'Confirmación de audio para acciones',
    'settings.haptic_feedback': 'Retroalimentación háptica',
    'settings.haptic_feedback_desc': 'Vibración para interacciones táctiles',
    'settings.notifications': 'Notificaciones',
    'settings.medication_reminders': 'Recordatorios de medicamentos',
    'settings.medication_reminders_desc': 'Recibe notificaciones cuando sea hora de tomar medicamentos',
    'settings.health_check_reminders': 'Recordatorios de chequeo de salud',
    'settings.health_check_reminders_desc': 'Recordatorios para monitoreo regular de salud',
    'settings.activity_reminders': 'Recordatorios de actividad',
    'settings.activity_reminders_desc': 'Recordatorios suaves para actividades diarias',
    'settings.emergency_alerts': 'Alertas de emergencia',
    'settings.emergency_alerts_desc': 'Notificaciones críticas de salud y seguridad',
    'settings.quiet_hours': 'Horas silenciosas',
    'settings.privacy_sharing': 'Privacidad y uso compartido',
    'settings.share_family': 'Compartir con familia',
    'settings.share_family_desc': 'Permitir que los miembros de la familia vean tus datos de salud',
    'settings.share_doctor': 'Compartir con médico',
    'settings.share_doctor_desc': 'Permitir que los proveedores de atención médica accedan a tus datos',
    'settings.location_tracking': 'Seguimiento de ubicación',
    'settings.location_tracking_desc': 'Rastrear ubicación para servicios de emergencia',
    'settings.data_backup': 'Copia de seguridad de datos',
    'settings.data_backup_desc': 'Copia de seguridad automática de tus datos de salud',
    'settings.app_preferences': 'Preferencias de la aplicación',
    'settings.language': 'Idioma',
    'settings.time_format': 'Formato de hora',
    'settings.auto_lock': 'Bloqueo automático',
    'settings.data_account': 'Datos y cuenta',
    'settings.export_data': 'Exportar datos',
    'settings.export_data_desc': 'Descargar tus datos de salud',
    'settings.reset_settings': 'Restablecer configuración',
    'settings.reset_settings_desc': 'Restaurar configuración predeterminada',
    'settings.delete_account': 'Eliminar cuenta',
    'settings.delete_account_desc': 'Eliminar permanentemente tu cuenta',
    'font_size.title': 'Tamaño de fuente',
    'font_size.desc': 'Ajusta el tamaño del texto en toda la aplicación para una mejor legibilidad.',
    'font_size.small': 'Pequeño (85%)',
    'font_size.small_desc': 'Recomendado para pantallas compactas',
    'font_size.medium': 'Mediano (100%)',
    'font_size.medium_desc': 'Tamaño predeterminado',
    'font_size.large': 'Grande (125%)',
    'font_size.large_desc': 'Más fácil de leer',
    'font_size.extra_large': 'Extra grande (150%)',
    'font_size.extra_large_desc': 'Máxima legibilidad',
  },
  French: {
    'auth.welcome_back': 'Bon retour!',
    'auth.create_account': 'Créer un compte',
    'auth.sign_in_continue': 'Connectez-vous pour poursuivre votre parcours de santé',
    'auth.create_get_started': 'Créez votre compte pour commencer avec des soins personnalisés',
    'auth.first_name': 'Prénom',
    'auth.last_name': 'Nom de famille',
    'auth.email': 'Adresse e-mail',
    'auth.phone': 'Numéro de téléphone (Optionnel)',
    'auth.password': 'Mot de passe',
    'auth.confirm_password': 'Confirmer le mot de passe',
    'auth.sign_in': 'Se connecter',
    'auth.create_account_btn': 'Créer un compte',
    'auth.senior_looking': 'Une personne âgée cherchant du soutien en santé',
    'auth.caregiver': 'Un aidant ou membre de la famille',
    'auth.sign_up': 'Vous n\'avez pas de compte? S\'inscrire',
    'auth.sign_in_prompt': 'Vous avez déjà un compte? Se connecter',
    'auth.i_am': 'Je suis:',
    'main.welcome': 'Bienvenue',
    'main.ai_companion': 'Compagnon de santé IA',
    'main.monitor': 'Surveiller',
    'main.activities': 'Activités',
    'main.medication': 'Médicament',
    'main.dashboard': 'Tableau de bord',
    'main.chat_ai': 'Chatter avec l\'IA',
    'main.ai_easy': 'Laissez l\'IA faciliter les choses',
    'main.logout': 'Déconnexion',
    'settings.title': 'Paramètres',
    'settings.accessibility': 'Accessibilité',
    'settings.font_size': 'Taille de police',
    'settings.large_text': 'Grand texte',
    'settings.large_text_desc': 'Augmenter la taille du texte pour une meilleure lisibilité',
    'settings.high_contrast': 'Mode contraste élevé',
    'settings.high_contrast_desc': 'Contraste amélioré pour une meilleure visibilité',
    'settings.voice_feedback': 'Retour vocal',
    'settings.voice_feedback_desc': 'Confirmation audio pour les actions',
    'settings.haptic_feedback': 'Retour haptique',
    'settings.haptic_feedback_desc': 'Vibration pour les interactions tactiles',
    'settings.notifications': 'Notifications',
    'settings.medication_reminders': 'Rappels de médicaments',
    'settings.medication_reminders_desc': 'Recevoir des notifications lorsqu\'il est temps de prendre des médicaments',
    'settings.health_check_reminders': 'Rappels de contrôle de santé',
    'settings.health_check_reminders_desc': 'Rappels pour la surveillance régulière de la santé',
    'settings.activity_reminders': 'Rappels d\'activité',
    'settings.activity_reminders_desc': 'Rappels doux pour les activités quotidiennes',
    'settings.emergency_alerts': 'Alertes d\'urgence',
    'settings.emergency_alerts_desc': 'Notifications critiques de santé et de sécurité',
    'settings.quiet_hours': 'Heures silencieuses',
    'settings.privacy_sharing': 'Confidentialité et partage',
    'settings.share_family': 'Partager avec la famille',
    'settings.share_family_desc': 'Permettre aux membres de la famille de voir vos données de santé',
    'settings.share_doctor': 'Partager avec le médecin',
    'settings.share_doctor_desc': 'Permettre aux prestataires de soins d\'accéder à vos données',
    'settings.location_tracking': 'Suivi de localisation',
    'settings.location_tracking_desc': 'Suivre la localisation pour les services d\'urgence',
    'settings.data_backup': 'Sauvegarde des données',
    'settings.data_backup_desc': 'Sauvegarder automatiquement vos données de santé',
    'settings.app_preferences': 'Préférences de l\'application',
    'settings.language': 'Langue',
    'settings.time_format': 'Format de l\'heure',
    'settings.auto_lock': 'Verrouillage automatique',
    'settings.data_account': 'Données et compte',
    'settings.export_data': 'Exporter les données',
    'settings.export_data_desc': 'Télécharger vos données de santé',
    'settings.reset_settings': 'Réinitialiser les paramètres',
    'settings.reset_settings_desc': 'Restaurer les paramètres par défaut',
    'settings.delete_account': 'Supprimer le compte',
    'settings.delete_account_desc': 'Supprimer définitivement votre compte',
    'font_size.title': 'Taille de police',
    'font_size.desc': 'Ajustez la taille du texte dans toute l\'application pour une meilleure lisibilité.',
    'font_size.small': 'Petit (85%)',
    'font_size.small_desc': 'Recommandé pour les écrans compacts',
    'font_size.medium': 'Moyen (100%)',
    'font_size.medium_desc': 'Taille par défaut',
    'font_size.large': 'Grand (125%)',
    'font_size.large_desc': 'Plus facile à lire',
    'font_size.extra_large': 'Très grand (150%)',
    'font_size.extra_large_desc': 'Lisibilité maximale',
  },
  German: {
    'auth.welcome_back': 'Willkommen zurück!',
    'auth.create_account': 'Konto erstellen',
    'auth.sign_in_continue': 'Melden Sie sich an, um Ihre Gesundheitsreise fortzusetzen',
    'auth.create_get_started': 'Erstellen Sie Ihr Konto, um mit personalisierter Pflege zu beginnen',
    'auth.first_name': 'Vorname',
    'auth.last_name': 'Nachname',
    'auth.email': 'E-Mail-Adresse',
    'auth.phone': 'Telefonnummer (Optional)',
    'auth.password': 'Passwort',
    'auth.confirm_password': 'Passwort bestätigen',
    'auth.sign_in': 'Anmelden',
    'auth.create_account_btn': 'Konto erstellen',
    'auth.senior_looking': 'Ein Senior, der Gesundheitsunterstützung sucht',
    'auth.caregiver': 'Ein Betreuer oder Familienmitglied',
    'auth.sign_up': 'Haben Sie kein Konto? Registrieren',
    'auth.sign_in_prompt': 'Haben Sie bereits ein Konto? Anmelden',
    'auth.i_am': 'Ich bin:',
    'main.welcome': 'Willkommen',
    'main.ai_companion': 'KI-Gesundheitsbegleiter',
    'main.monitor': 'Überwachen',
    'main.activities': 'Aktivitäten',
    'main.medication': 'Medikamente',
    'main.dashboard': 'Dashboard',
    'main.chat_ai': 'Mit KI chatten',
    'main.ai_easy': 'Lassen Sie KI die Dinge einfacher machen',
    'main.logout': 'Abmelden',
    'settings.title': 'Einstellungen',
    'settings.accessibility': 'Barrierefreiheit',
    'settings.font_size': 'Schriftgröße',
    'settings.large_text': 'Großer Text',
    'settings.large_text_desc': 'Textgröße für bessere Lesbarkeit erhöhen',
    'settings.high_contrast': 'Hoher Kontrast Modus',
    'settings.high_contrast_desc': 'Verbesserter Kontrast für bessere Sichtbarkeit',
    'settings.voice_feedback': 'Sprach-Feedback',
    'settings.voice_feedback_desc': 'Audio-Bestätigung für Aktionen',
    'settings.haptic_feedback': 'Haptisches Feedback',
    'settings.haptic_feedback_desc': 'Vibration für Berührungsinteraktionen',
    'settings.notifications': 'Benachrichtigungen',
    'settings.medication_reminders': 'Medikamentenerinnerungen',
    'settings.medication_reminders_desc': 'Benachrichtigungen erhalten, wenn es Zeit ist, Medikamente einzunehmen',
    'settings.health_check_reminders': 'Gesundheitsprüfungserinnerungen',
    'settings.health_check_reminders_desc': 'Erinnerungen für regelmäßige Gesundheitsüberwachung',
    'settings.activity_reminders': 'Aktivitätserinnerungen',
    'settings.activity_reminders_desc': 'Sanfte Erinnerungen für tägliche Aktivitäten',
    'settings.emergency_alerts': 'Notfallwarnungen',
    'settings.emergency_alerts_desc': 'Kritische Gesundheits- und Sicherheitsbenachrichtigungen',
    'settings.quiet_hours': 'Ruhezeiten',
    'settings.privacy_sharing': 'Datenschutz & Teilen',
    'settings.share_family': 'Mit Familie teilen',
    'settings.share_family_desc': 'Familienmitgliedern erlauben, Ihre Gesundheitsdaten einzusehen',
    'settings.share_doctor': 'Mit Arzt teilen',
    'settings.share_doctor_desc': 'Gesundheitsdienstleistern Zugriff auf Ihre Daten gewähren',
    'settings.location_tracking': 'Standortverfolgung',
    'settings.location_tracking_desc': 'Standort für Notdienste verfolgen',
    'settings.data_backup': 'Datensicherung',
    'settings.data_backup_desc': 'Ihre Gesundheitsdaten automatisch sichern',
    'settings.app_preferences': 'App-Einstellungen',
    'settings.language': 'Sprache',
    'settings.time_format': 'Zeitformat',
    'settings.auto_lock': 'Automatische Sperre',
    'settings.data_account': 'Datos & Konto',
    'settings.export_data': 'Daten exportieren',
    'settings.export_data_desc': 'Ihre Gesundheitsdaten herunterladen',
    'settings.reset_settings': 'Einstellungen zurücksetzen',
    'settings.reset_settings_desc': 'Standardeinstellungen wiederherstellen',
    'settings.delete_account': 'Konto löschen',
    'settings.delete_account_desc': 'Ihr Konto dauerhaft löschen',
    'font_size.title': 'Schriftgröße',
    'font_size.desc': 'Passen Sie die Textgröße in der gesamten App an, um die Lesbarkeit zu verbessern.',
    'font_size.small': 'Klein (85%)',
    'font_size.small_desc': 'Empfohlen für kompakte Bildschirme',
    'font_size.medium': 'Mittel (100%)',
    'font_size.medium_desc': 'Standardgröße',
    'font_size.large': 'Groß (125%)',
    'font_size.large_desc': 'Einfacher zu lesen',
    'font_size.extra_large': 'Extra groß (150%)',
    'font_size.extra_large_desc': 'Maximale Lesbarkeit',
  },
  Chinese: {
    'auth.welcome_back': '欢迎回来！',
    'auth.create_account': '创建账户',
    'auth.sign_in_continue': '登录以继续您的健康之旅',
    'auth.create_get_started': '创建您的账户以开始个性化护理',
    'auth.first_name': '名字',
    'auth.last_name': '姓氏',
    'auth.email': '电子邮箱',
    'auth.phone': '电话号码（可选）',
    'auth.password': '密码',
    'auth.confirm_password': '确认密码',
    'auth.sign_in': '登录',
    'auth.create_account_btn': '创建账户',
    'auth.senior_looking': '寻求健康支持的老年人',
    'auth.caregiver': '护理人员或家庭成员',
    'auth.sign_up': '没有账户？注册',
    'auth.sign_in_prompt': '已有账户？登录',
    'auth.i_am': '我是:',
    'main.welcome': '欢迎',
    'main.ai_companion': 'AI健康伴侣',
    'main.monitor': '监测',
    'main.activities': '活动',
    'main.medication': '药物',
    'main.dashboard': '仪表板',
    'main.chat_ai': '与AI聊天',
    'main.ai_easy': '让AI让事情变得更简单',
    'main.logout': '登出',
    'settings.title': '设置',
    'settings.accessibility': '无障碍',
    'settings.font_size': '字体大小',
    'settings.large_text': '大字体',
    'settings.large_text_desc': '增大文本大小以提高可读性',
    'settings.high_contrast': '高对比度模式',
    'settings.high_contrast_desc': '增强对比度以提高可见性',
    'settings.voice_feedback': '语音反馈',
    'settings.voice_feedback_desc': '操作的音频确认',
    'settings.haptic_feedback': '触觉反馈',
    'settings.haptic_feedback_desc': '触摸交互的振动反馈',
    'settings.notifications': '通知',
    'settings.medication_reminders': '药物提醒',
    'settings.medication_reminders_desc': '服药时间时收到通知',
    'settings.health_check_reminders': '健康检查提醒',
    'settings.health_check_reminders_desc': '定期健康监测提醒',
    'settings.activity_reminders': '活动提醒',
    'settings.activity_reminders_desc': '日常活动的温和提醒',
    'settings.emergency_alerts': '紧急警报',
    'settings.emergency_alerts_desc': '关键的健康和安全管理通知',
    'settings.quiet_hours': '安静时间',
    'settings.privacy_sharing': '隐私与共享',
    'settings.share_family': '与家人共享',
    'settings.share_family_desc': '允许家人查看您的健康数据',
    'settings.share_doctor': '与医生共享',
    'settings.share_doctor_desc': '允许医疗保健提供者访问您的数据',
    'settings.location_tracking': '位置跟踪',
    'settings.location_tracking_desc': '为紧急服务跟踪位置',
    'settings.data_backup': '数据备份',
    'settings.data_backup_desc': '自动备份您的健康数据',
    'settings.app_preferences': '应用偏好',
    'settings.language': '语言',
    'settings.time_format': '时间格式',
    'settings.auto_lock': '自动锁定',
    'settings.data_account': '数据和账户',
    'settings.export_data': '导出数据',
    'settings.export_data_desc': '下载您的健康数据',
    'settings.reset_settings': '重置设置',
    'settings.reset_settings_desc': '恢复默认设置',
    'settings.delete_account': '删除账户',
    'settings.delete_account_desc': '永久删除您的账户',
    'font_size.title': '字体大小',
    'font_size.desc': '调整整个应用的文本大小以提高可读性。',
    'font_size.small': '小 (85%)',
    'font_size.small_desc': '推荐用于紧凑屏幕',
    'font_size.medium': '中 (100%)',
    'font_size.medium_desc': '默认大小',
    'font_size.large': '大 (125%)',
    'font_size.large_desc': '更易阅读',
    'font_size.extra_large': '特大 (150%)',
    'font_size.extra_large_desc': '最大可读性',
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('English');

  // Load language from AsyncStorage on mount
  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const storedLanguage = await AsyncStorage.getItem(LANGUAGE_STORAGE_KEY);
        if (storedLanguage && ['English', 'Spanish', 'French', 'German', 'Chinese'].includes(storedLanguage)) {
          setLanguage(storedLanguage as Language);
        }
      } catch (error) {
        console.error('Failed to load language from AsyncStorage', error);
      }
    };
    loadLanguage();
  }, []);

  // Save language to AsyncStorage whenever it changes
  useEffect(() => {
    const saveLanguage = async () => {
      try {
        await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, language);
      } catch (error) {
        console.error('Failed to save language to AsyncStorage', error);
      }
    };
    saveLanguage();
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations.English[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

