// Icon helper to map Ionicons names to react-icons
import { 
  IoMdSettings as SettingsOutline,
  IoMdLogOut as LogOut,
  IoMdHeart as HeartOutline,
  IoMdHeartEmpty as HeartEmpty,
  IoMdFitness as FitnessOutline,
  IoMdMedical as MedicalOutline,
  IoMdAnalytics as AnalyticsOutline,
  IoMdChatbubbles as ChatbubblesOutline,
  IoMdArrowBack as ArrowBack,
  IoMdClose as Close,
  IoMdCheckmark as Checkmark,
  IoMdAdd as Add,
  IoMdRemove as Remove,
  IoMdTime as TimeOutline,
  IoMdCalendar as CalendarOutline,
  IoMdPeople as PeopleOutline,
  IoMdPerson as PersonOutline,
  IoMdLocation as LocationOutline,
  IoMdCloudUpload as CloudOutline,
  IoMdRefresh as RefreshOutline,
  IoMdTrash as TrashOutline,
  IoMdDownload as DownloadOutline,
  IoMdLockClosed as LockClosedOutline,
  IoMdVolumeHigh as VolumeHighOutline,
  IoMdPhonePortrait as PhonePortraitOutline,
  IoMdWarning as WarningOutline,
  IoMdMoon as MoonOutline,
  IoMdLanguage as LanguageOutline,
  IoMdText as TextOutline,
  IoMdContrast as ContrastOutline,
  IoMdPencil as Pencil,
  IoMdCheckmarkCircle as CheckmarkCircle,
  IoMdWater as WaterOutline,
  IoMdHandLeft as HandLeftOutline,
  IoMdAirplane as AirplaneOutline,
  IoMdArrowForward as ArrowForward,
  IoMdPulse as PulseOutline,
  IoMdThermometer as ThermometerOutline,
  IoMdScale as ScaleOutline,
  IoMdBulb as BulbOutline,
} from 'react-icons/io';

// Map of icon names to components
export const Icons: Record<string, React.ComponentType<any>> = {
  'settings-outline': SettingsOutline,
  'log-out-outline': LogOut,
  'heart-outline': HeartOutline,
  'heart': HeartEmpty,
  'fitness-outline': FitnessOutline,
  'medical-outline': MedicalOutline,
  'analytics-outline': AnalyticsOutline,
  'chatbubbles-outline': ChatbubblesOutline,
  'arrow-back': ArrowBack,
  'close': Close,
  'checkmark': Checkmark,
  'add': Add,
  'remove': Remove,
  'time-outline': TimeOutline,
  'calendar-outline': CalendarOutline,
  'people-outline': PeopleOutline,
  'person-outline': PersonOutline,
  'location-outline': LocationOutline,
  'cloud-outline': CloudOutline,
  'refresh-outline': RefreshOutline,
  'trash-outline': TrashOutline,
  'download-outline': DownloadOutline,
  'lock-closed-outline': LockClosedOutline,
  'volume-high-outline': VolumeHighOutline,
  'phone-portrait-outline': PhonePortraitOutline,
  'warning-outline': WarningOutline,
  'moon-outline': MoonOutline,
  'language-outline': LanguageOutline,
  'text-outline': TextOutline,
  'contrast-outline': ContrastOutline,
  'pencil': Pencil,
  'checkmark-circle': CheckmarkCircle,
  'water-outline': WaterOutline,
  'hand-left-outline': HandLeftOutline,
  'airplane-outline': AirplaneOutline,
  'arrow-forward': ArrowForward,
  'pulse-outline': PulseOutline,
  'thermometer-outline': ThermometerOutline,
  'scale-outline': ScaleOutline,
  'bulb-outline': BulbOutline,
};

export const Icon = ({ name, size = 24, color = '#FFFFFF', style }: { name: string; size?: number; color?: string; style?: React.CSSProperties }) => {
  const IconComponent = Icons[name] || Icons['close'];
  return <IconComponent size={size} color={color} style={style} />;
};

